name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_NOTION_API_KEY: ${{ secrets.NEXT_PUBLIC_NOTION_API_KEY }}
      NEXT_PUBLIC_NOTION_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_NOTION_DATABASE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "NFAP0221S"
          git config --global user.email "vawav11@gmail.com"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTION_TOKEN }}@github.com/NFAP0221S/NFAP0221S.github.io.git
          npm run deploy

      - name: nojekyll setup
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          git clone --branch gh-pages https://x-access-token:${{ secrets.ACTION_TOKEN }}@github.com/NFAP0221S/NFAP0221S.github.io.git gh-pages
          echo "" > gh-pages/.nojekyll
          cd gh-pages
          git add .nojekyll
          git commit -m "Add .nojekyll file" || echo "No changes to commit"
          git push origin gh-pages