name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_NOTION_API_KEY: ${{ secrets.NEXT_PUBLIC_NOTION_API_KEY }}
      NEXT_PUBLIC_NOTION_DATABASE_ID: ${{ secrets.NEXT_PUBLIC_NOTION_DATABASE_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      # - name: Setup environment variables
      #   run: |

      - name: Install dependencies
        working-directory: ./gpblog
        run: npm install

      - name: Build project
        working-directory: ./gpblog
        run: npm run build

      - run: touch out/.nojekyll

      # - name: Export static files
      #   working-directory: ./gpblog
      #   run: npm run export
      - name: Configure Git
        run: |
          git config --global user.name "NFAP0221S"
          git config --global user.email "vawav11@gmail.com"

      - name: Deploy to GitHub Pages
        working-directory: ./gpblog
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: npm run deploy
