name: Test SSH Key

on:
  push:
    branches:
      - main

jobs:
  test-ssh-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        id: ssh-agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Test SSH Key
        run: echo "SSH Key has been added successfully"